### ISSUE TITLE
TiDB 单机版部署

### ISSUE THREAD

**Issue by Jengro777** [xxxily/local-appstore-for-1Panel#4]
https://github.com/pingcap/tidb-docker-compose
TiDB 单机版部署

```
version: '3'

services:
  pd1:
    image: pingcap/pd:latest
    ports:
      - "2379"
    volumes:
      - ./pd_data:/pd
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd1:2379
      - --advertise-peer-urls=http://pd1:2380
      - --initial-cluster=pd1=http://pd1:2380
      - --data-dir=/pd
    restart: always
    networks:
      - tidb_net
  tikv1:
    image: pingcap/tikv:latest
    volumes:
      - ./tikv_data:/tikv
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --pd=pd1:2379
      - --data-dir=/tikv
    depends_on:
      - "pd1"
    restart: always
    networks:
      - tidb_net
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --store=tikv
      - --path=pd1:2379
      - --advertise-address=tidb
    depends_on:
      - "tikv1"
    restart: always
    networks:
      tidb_net:
        ipv4_address: 192.168.88.30

networks:
  tidb_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
```
